models/Customer.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "customer".
 *
 * @property int $id
 * @property string $firstname
 * @property string $lastname
 * @property string $contactnumber
 * @property string $streetname
 * @property int $housenumber
 * @property string $cityname
 * @property int $zipcode
 * @property string $iban
 * @property string $accountowner
 */
class Customer extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'customer';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['firstname', 'lastname', 'contactnumber', 'streetname', 'housenumber', 'cityname', 'zipcode', 'iban', 'accountowner'], 'required'],
            [['housenumber', 'zipcode'], 'integer'],
            [['firstname', 'lastname', 'contactnumber', 'streetname', 'cityname', 'iban', 'accountowner'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'firstname' => 'Firstname',
            'lastname' => 'Lastname',
            'contactnumber' => 'Contactnumber',
            'streetname' => 'Streetname',
            'housenumber' => 'Housenumber',
            'cityname' => 'Cityname',
            'zipcode' => 'Zipcode',
            'iban' => 'Iban',
            'accountowner' => 'Accountowner',
        ];
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\web\Response;
use app\models\Customer;

class SiteController extends Controller
{
    public function actionIndex()
    {	
    	$session = Yii::$app->session;  

    	if($session->has('personal_done'))
    	{
    		$this->redirect('address');
    	}
    	else
    	{
        	return $this->render('personal');	
    	}
    }

    public function actionHandlePersonal()
    {
    	$session = Yii::$app->session;  
        $session->set('personal_done', '1');

        $request = Yii::$app->request;

        $firstname = $request->post('first-name');
        $lastname = $request->post('last-name');
        $contactnumber = $request->post('contact-number');

        $session->set('firstname', $firstname);
        $session->set('lastname', $lastname);
        $session->set('contactnumber', $contactnumber);

        $this->redirect('address');
    }

    public function actionAddress()
    {	
    	$session = Yii::$app->session; 
    	if($session->has('address_done')) 
    	{
    		$this->redirect('payment');
        } 
        else if($session->has('personal_done')) 
        {
			return $this->render('address');
        }
        else
        {
        	$this->redirect('/');
        }
    }

    public function actionHandleAddress()
    {
    	$session = Yii::$app->session;  
        $session->set('address_done', '1');

        $request = Yii::$app->request;

        $streetname = $request->post('street-name');
        $housenumber = $request->post('house-number');
        $cityname = $request->post('city-name');
        $zipcode = $request->post('zip-code');

        $session->set('streetname', $streetname);
        $session->set('housenumber', $housenumber);
        $session->set('cityname', $cityname);
        $session->set('zipcode', $zipcode);

        $this->redirect('payment');
    }

    public function actionPayment()
    {
    	$session = Yii::$app->session; 
    	if($session->has('payment_done')) 
    	{
    		$this->redirect('success');
        } 
        else if($session->has('personal_done') && $session->has('address_done'))
        {
        	return $this->render('payment');
        }
        else
        {
        	$this->redirect('/');
        }
    }

    public function actionHandlePayment()
    {
    	$session = Yii::$app->session;  
    	$request = Yii::$app->request;

        $session->set('payment_done', '1');

        $model = new Customer;
        $model->firstname = $session->get('firstname');
        $model->lastname = $session->get('lastname');
        $model->contactnumber = $session->get('contactnumber');
        $model->streetname = $session->get('streetname');
        $model->housenumber = $session->get('housenumber');
        $model->cityname = $session->get('cityname');
        $model->zipcode = $session->get('zipcode');
        $model->iban = $request->post('iban');
        $model->accountowner = $request->post('account-owner');
        $model->save();

        $id = $model->find()->max('id');
        $data = array(
	    	'customerId' => $id, 
	    	'iban' => $request->post('iban'),
	    	'owner' => $request->post('account-owner')
	  	);  

		$json_data = json_encode($data);

		$url = 'https://37f32cl571.execute-api.eu-central-1.amazonaws.com/default/wunderfleet-recruiting-backend-dev-save-payment-data';

		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, $url);
		curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json'));
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS,$json_data);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		$result  = curl_exec($ch);

		curl_close($ch);

		$decode_data = json_decode($result);
		$current = Customer::findOne($id);
		$current->paymentdataid = $decode_data->paymentDataId;
		$current->save();

		$session->set('paymentdataid', $decode_data->paymentDataId);

    	$this->redirect('success');
    }

    public function actionSuccess()
    {
    	$session = Yii::$app->session; 
    	if($session->has('personal_done') && $session->has('address_done') && $session->has('payment_done'))
    	{
        	return $this->render('success');
    	}
    	else
    	{
    		$this->redirect('/');
    	}
    }

    public function actionRestart()
    {
    	$session = Yii::$app->session; 
    	$session->destroy();
        $this->redirect('/');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>

<?php $this->beginPage() ?>
<!doctype html>
<html lang="en">
   <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <link href="https://fonts.googleapis.com/css?family=Niramit|Roboto" rel="stylesheet">
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
         rel="stylesheet">

      <!-- Main CSS -->
      <link rel="stylesheet" href="<?php echo Yii::$app->request->baseUrl;; ?>/css/main.css" >

      <!-- Scripts -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

      <title>Wunder Registration</title>
   </head>
   <body>
<?php $this->beginBody() ?>
    <?= $content ?>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/address.php
<?php
   use yii\helpers\Url;
?>
<div class="container">
   <div class="row">
      <div class="col-md-8 offset-md-2 nopadding">
         <div class="col-md-4">
            <div class="titlebox">
               <h4> ADDRESS </h4>
            </div>
         </div>
         <div class="box">
            <form action="<?php echo Url::to(['site/handle-address']);?>" method="POST">
               <input type="hidden" name="_csrf" value="<?=Yii::$app->request->getCsrfToken()?>" />
               <div class="form-group col-md-6 offset-md-3">
                  <label for="street-name"><b>Street</b></label>
                  <input type="text" class="form-control inputbox" name="street-name" placeholder="Enter your Street Name" pattern="[a-z A-Z-0-9#,.]{2,30}" title="Street Name must include a minimum of 2 and a maximum of 30 alphanumeric characters, periods, commas, and hashes only." required>
               </div>
               <div class="form-group col-md-6 offset-md-3">
                  <label for="house-number"><b>House Number</b></label>
                  <input type="text" class="form-control inputbox" name="house-number" placeholder="Enter your House Number" pattern="[0-9]{1,10}" title="House number must include a minimum of 2 and a maximum of 10 numeric characters only." required>
               </div>
               <div class="form-group col-md-6 offset-md-3">
                  <label for="city-name"><b>City</b></label>
                  <input type="text" class="form-control inputbox" name="city-name" placeholder="Enter your City" pattern="[a-z A-Z]{2,30}" title="City must include a minimum of 2 and a maximum of 30 alphabetical characters only." required>
               </div>
               <div class="form-group col-md-6 offset-md-3">
                  <label for="zip-code"><b>Zip Code</b></label>
                  <input type="text" class="form-control inputbox" name="zip-code" placeholder="Enter your Zip Code" pattern="[0-9]{3,10}" title="House number must include a minimum of 3 and a maximum of 10 numeric characters only." required>
               </div>
               <div class="col-md-6 offset-3">
                  <center>
                     <br><br><button type="submit" class="btn custom-button"><strong>NEXT</strong></button>
                  </center>
               </div>
            </form>
         </div>
      </div>
   </div>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/payment.php
<?php
	use yii\helpers\Url;
?>
<div class="container">
	<div class="row">
		<div class="col-md-8 offset-md-2 nopadding">
			<div class="col-md-4">
				<div class="titlebox">
					<h4> PAYMENT </h4>
				</div>
			</div>
			<div class="box">
				<form action="<?php echo Url::to(['site/handle-payment']);?>" method="POST">
               	<input type="hidden" name="_csrf" value="<?=Yii::$app->request->getCsrfToken()?>" />
					<div class="form-group col-md-6 offset-md-3">
						<label for="account-owner"><b>Account Owner</b></label>
						<input type="text" class="form-control inputbox" id="account-owner" name="account-owner" placeholder="Enter the Account Owner" pattern="[a-z A-Z]{2,30}" title="Account Owner must include a minimum of 2 and a maximum of 30 alphabetical characters only" required>
					</div>
					<div class="form-group col-md-6 offset-md-3">
						<label for="iban"><b>IBAN</b></label>
						<input type="text" class="form-control inputbox" id="iban" name="iban" placeholder="Enter the IBAN" pattern="[0-9 A-Z]{1,34}" title="IBAN must include a minimum of 1 and a maximum of 34 alphanumeric characters only." required>
					</div>
					<div class="col-md-6 offset-3">
						<center>
						<br><br><button type="submit" id="submitBtn" class="btn custom-button">SUBMIT</button></center>
						</center>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

views/site/personal.php
<?php
   use yii\helpers\Url;
?>
<div class="container">
   <div class="row">
      <div class="col-md-8 offset-md-2 nopadding">
         <div class="col-md-4">
            <div class="titlebox">
               <h4> PERSONAL</h4>
            </div>
         </div>
         <div class="box">
            <form action="<?php echo Url::to(['site/handle-personal']);?>" method="POST">
               <input type="hidden" name="_csrf" value="<?=Yii::$app->request->getCsrfToken()?>" />
               <div class="form-group col-md-6 offset-md-3">
                  <label for="first-name"><b>First Name</b></label>
                  <input type="text" class="form-control inputbox" name="first-name" placeholder="Enter your First Name" pattern="[a-z A-Z]{2,30}" title="First Name must include a minimum of 2 and a maximum of 30 alphabetical characters only." required>
               </div>
               <div class="form-group col-md-6 offset-md-3">
                  <label for="last-name"><b>Last Name</b></label>
                  <input type="text" class="form-control inputbox" name="last-name" placeholder="Enter your Last Name" pattern="[a-z A-Z]{2,30}" title="Last Name must include a minimum of 2 and a maximum of 30 alphabetical characters only." required>
               </div>
               <div class="form-group col-md-6 offset-md-3">
                  <label for="contact-number"><b>Contact Number</b></label>
                  <input type="text" class="form-control inputbox" name="contact-number" placeholder="Enter your Contact #" pattern="[-0-9()]{6,}" title="Contact number should contain numbers and parentheses only, with a minimum of 6 characters." required>
               </div>
               <div class="col-md-6 offset-3">
                  <center>
                  <br><br><button type="submit" class="btn custom-button"><strong>NEXT</strong></button>
                  </center>
               </div>
            </form>
         </div>
      </div>
   </div>
</div>

views/site/success.php
<?php
   use yii\helpers\Url;
?>
<div class="container">
   <div class="row">
      <div class="col-md-12">
         <div class="box">
            <div class="text-center" style="margin-bottom: 30px">
               <img src="http://www.dovera.sk/media/!media/!media/micro_2015_cukrovka/img/svg/icon--checkmark.svg" height="80px" width="80px" class="text-center" />
            </div>
            <h1 class="text-center"> Thank you! </h1>
            <h3 class="text-center"> Your registration is successful! </h3>
            <br><br>
            <h3 class="text-center"> Your Payment Data ID is:  </h3>
            <strong><h3 class="text-center" style="font-size: 15px"> <?php echo Yii::$app->session->get('paymentdataid');?> </h3></strong>
            <div class="col-md-6 offset-3">
               <center>
               <br><br><button type="submit" id="submitBtn" class="btn custom-button"> Back to Registration</button></center>
               </center>
            </div>
         </div>
      </div>
   </div>
</div>

<script type="text/javascript">
   const url = '<?php echo Url::to(['site/restart']);?>';

   $(document).ready(function(){
      $('#submitBtn').on('click', function() {
         $.ajax({
             type:'GET',
             url: url,
             success:function(result){
             },
              error: function(xhr, ajaxOptions, thrownError){
                 console.log(xhr.status);
             },
         }); 
      });
   });
</script>